# Generated by Django 3.2.4 on 2021-06-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210612_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile',
            field=models.ImageField(blank=True, default='static/image/profile1.png', null=True, upload_to=''),
        ),
    ]
